/**
 * Embeds schema.sql as a string constant in src/shared/schema-sql.generated.ts.
 *
 * Why: `initDb()` used to resolve schema.sql's path at runtime relative to
 * import.meta.dirname / process.cwd(). That breaks the moment a consumer's
 * bundler (e.g. Vite/Astro) inlines this package into a single SSR chunk —
 * the directory-depth assumptions no longer hold and schema.sql can't be
 * found on disk. Embedding the content as a string sidesteps path
 * resolution entirely, so it survives bundling.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const schemaSql = readFileSync(join(root, "schema.sql"), "utf-8");
const outPath = join(root, "src", "shared", "schema-sql.generated.ts");

writeFileSync(
  outPath,
  `// Generated by scripts/generate-schema-module.ts from schema.sql. Do not edit.\nexport const SCHEMA_SQL = ${JSON.stringify(schemaSql)};\n`
);

console.log(`wrote ${outPath}`);
